### ISSUE TITLE
Problem with setup

### ISSUE THREAD

**Issue by DannyJiang1** [chiyadev/MudaeFarm#101]
Hello, after extracting and running Mudaefarm.exe, I get 'failed to load profiles', I go to the folder itself and made a json file named "profiles.json", and I followed the instructions from the other post, pasting the code inside it:
{
"default": ""
}
But I'm still getting the exact same error.

**Comment by phosphene47** [comment]
Possibly fixed with #96. Please tell me to reopen if this persists.
