### ISSUE TITLE
Bug on kakera collecting - Infinite $tu loop

### ISSUE THREAD

**Issue by ssj4maiko** [chiyadev/MudaeFarm#103]
This has repeated recently many times to me, I always checked what could be the reason, and so I think I found it. These are the settings to reproduce it:

```
{
  "enabled": true,
  "fallback_status": "Idle",
  "state_update_command": "$tu auto"
}
{
  "enabled": true,
  "delay_seconds": 60.0,
  "kakera_delay_seconds": 30.0,
  "kakera_targets": [
    "Purple",
    "Yellow",
    "Orange",
    "Red",
    "Rainbow"
  ],
  "enable_custom_emotes": false
}
{
  "enabled": true,
  "command": "$wb auto",
  "roll_with_no_claim": true,
  "daily_kakera_enabled": false,
  "daily_kakera_command": "$dk",
  "daily_kakera_then_state_update": false,
  "typing_delay_seconds": 0.8,
  "interval_override_minutes": null
}
```
Let's say there were 20 rolls in less than 30 seconds, and there were 2 or more kakera rolls on those that fit the targets.
My guess is: The trigger to the get kakera event will start, and will wait 30 seconds as per setting, but because there will be 2 or more rolls (with $setrare1, there are consecutive ones a number of times), it seems to bug out, and soon after it  starts repeating the "state_update_command" command ad infinitum.

The log just states that it is running the state_update_command (Likely to confirm how much kakera react power it still has), however, it will never read it (On the logs, there are only repeated messages of sending the command, but it never shows the compiled json).

Even if I delete all data from #bot-channels, it will still spam the trigger command non-stop.

**Comment by ssj4maiko** [comment]
So, to avoid this problem, I simply set the timing pretty low (0.5), and there was this one time that, after claiming the kakera, it used the "$tu auto", however, the mudamaid seemed to have taken some time to respond, and the bot called the command again. I don't know what happened, but it started looping, it went for a few seconds, but after about a minute or so, while I was moving to turn it of in the other PC... It stopped.

So I'm positing just in case it may hint to the real problem.

**Comment by phosphene47** [comment]
[v4](https://github.com/chiyadev/MudaeFarm/releases/tag/v4.0.0) no longer uses `$tu`.
