### ISSUE TITLE
Not rolling $w because we cannot claim

### ISSUE THREAD

**Issue by preintercede** [chiyadev/MudaeFarm#104]
Not sure what happened overnight, but my console has been saying "not rolling $w because we cannot claim" even though I can claim. I only have 1 character on my wishlist anyways and she hasn't popped up. I checked message history and I have not married anyone. I noticed it continued to not roll since then even though the rolling period has reset a few times. It still continued to do $tu although there were a few periods of time where it skipped. The $tu showed that I could claim a character too.

**Comment by phosphene47** [comment]
Rolling behavior has changed in [v4](https://github.com/chiyadev/MudaeFarm/releases/tag/v4.0.0). Bot will always attempt to roll, and only after rolling will it determine its success.
