### ISSUE TITLE
bot doesn't claim in other languages?

### ISSUE THREAD

**Issue by Latekek** [chiyadev/MudaeFarm#105]
hi so today i used the bot for the first time and saw that he doesn't claim 
is that normal ? the bot says can't claim because of a cooldown or something even if i can claim 
bot language was changed to german from the server owner i guess 
![Screenshot_1](https://user-images.githubusercontent.com/62397695/77098406-9af62680-6a12-11ea-93ff-a35f17f32c66.png)
Edit : works fine for english discords so its the language i think

**Comment by phosphene47** [comment]
Yes, there is no support for languages other than English at the moment.

There is already an open issue regarding this #67. Closing this as duplicate.

**Comment by Latekek** [comment]
well i found the problem, the bot supported other languages you just have to switch the "$tu" thing to "" and then it works

**Comment by phosphene47** [comment]
That sounds like a valid workaround for now. I haven't tested that yet however.

**Comment by niqitowo** [comment]
What file should I modify?
