### ISSUE TITLE
Bot doesn't claim / too slow?

### ISSUE THREAD

**Issue by Latekek** [chiyadev/MudaeFarm#106]
So today i saw that the bot doesn't claim since yesterday, i changed the delay seconds to 1,5 and then back to 0.5 since that the bot doesn't claim how do i fix? He is saying that he's trying but he doesn't claim... 
![Screenshot_1](https://user-images.githubusercontent.com/62397695/77227742-bed87a00-6b82-11ea-949a-891b96c645a7.png)

**Comment by Latekek** [comment]
reinstalled the bot, deleted the old server configured everything again and now it works perfect again

**Comment by phosphene47** [comment]
Good to hear. Feel free to reopen if this occurs again.

**Comment by Latekek** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/62397695/77813005-8fa39a80-70a5-11ea-9ec0-f6a8eb6062b6.png)
it happens again, it's so annoying please fix it

**Comment by Latekek** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/62397695/77813130-5f103080-70a6-11ea-9871-9fdd3ec1e530.png)
