### ISSUE TITLE
Number of rolls is ignored when interval override is set

### ISSUE THREAD

**Issue by xMamex** [chiyadev/MudaeFarm#112]
Is it possible to make the bot auto roll more often without me having to type it? Right now the bot only rolls once every 5 minutes. I have auto rolling enabled.

**Comment by phosphene47** [comment]
Please see the [Miscellaneous](https://github.com/chiyadev/MudaeFarm#miscellaneous) section of the readme. The configuration you are looking for is `internal_override_minutes`.

**Comment by xMamex** [comment]
Ok, thanks!

**Comment by xMamex** [comment]
Wait... But now it won't stop rolling even though I don't have any more rolls. I wanted it to autoroll every .3 seconds so I set internal_override_minutes to .005 and then stop when I don't have more rolls.

**Comment by phosphene47** [comment]
Found [this line](https://github.com/chiyadev/MudaeFarm/blob/master/MudaeFarm/AutoRoller.cs#L103) which is responsible for determining roll interval. Currently it ignores the number of rolls left if you set an override.

**Comment by phosphene47** [comment]
[v4](https://github.com/chiyadev/MudaeFarm/releases/tag/v4.0.0) changes rolling behavior, so this issue is no longer relevant.
