### ISSUE TITLE
Not claiming

### ISSUE THREAD

**Issue by Bicsa** [chiyadev/MudaeFarm#113]
i've installed the bot twice and both time he tries to claim my wishlist but doesn't react
![test](https://user-images.githubusercontent.com/64423037/80386722-0fd93d80-88a8-11ea-90d6-0ca2ac21532d.PNG)

**Comment by Latekek** [comment]
set state_update_command: from "$tu" to "" and it should work

**Comment by phosphene47** [comment]
[v4](https://github.com/chiyadev/MudaeFarm/releases/tag/v4.0.0) no longer uses `state_update_command`.
