### ISSUE TITLE
Message before claiming

### ISSUE THREAD

**Issue by Restiasan** [chiyadev/MudaeFarm#114]
Is there a way to send a message before claiming instead of the actual message after claim?

**Comment by phosphene47** [comment]
[Nope](https://github.com/chiyadev/MudaeFarm/blob/master/MudaeFarm/AutoClaimer.cs#L195).

**Comment by phosphene47** [comment]
[Yes](https://github.com/chiyadev/MudaeFarm#claim-replies). You can use JSON object to configure claim reply with `event` set to `BeforeClaim`. There are examples.
