### ISSUE TITLE
any way to have this open 24/7

### ISSUE THREAD

**Issue by pinyo6** [chiyadev/MudaeFarm#115]
is there any way i can have this on 24/7 without having to have it open on my computer?

**Comment by pinyo6** [comment]
also when a character on my wishlist comes up it says
 [warn] [11:12:19] Za ServerT #waifus: Found character 'Rem', trying claim.
but doesnt actually claim

**Comment by phosphene47** [comment]
No, as with any program you must leave your computer running for MudaeFarm to work.

Your second issue seems to be a duplicate of https://github.com/chiyadev/MudaeFarm/issues/92, so I will close this issue.
