### ISSUE TITLE
Does this also work for the Mudamaid 7 bot?

### ISSUE THREAD

**Issue by pinyo6** [chiyadev/MudaeFarm#116]
so the server im in has the mudae bot as well as the mudamaid 7 bot, I'm wondering whether mudaefarm is not claiming because the server is using the mudamaid 7 bot or whether its just me settings things up wrong.

**Comment by phosphene47** [comment]
MudaeFarm should be able to recognize Mudae or any of its maids or butlers, independent of configuration.
