### ISSUE TITLE
The bot keeps sending my user id after claiming a wish?

### ISSUE THREAD

**Issue by Latekek** [chiyadev/MudaeFarm#118]
so everytime the bot claims a char / wish he sends my user id 
How do i fix that? in the logs it says "sent auto reply : id" can i deactivate that somehow?
![Screenshot_4](https://user-images.githubusercontent.com/62397695/81967499-4a1e3b00-961b-11ea-93e5-f4ceae8b5156.png)

**Comment by Latekek** [comment]
NEVER MIND I JUST POSTED MY ID IN CLAIM REPLIES I'M SO DUMB

**Comment by phosphene47** [comment]
Don't worry about it. People can make mistakes.

**Comment by Latekek** [comment]
thanks
