### ISSUE TITLE
Kakera claim delay?

### ISSUE THREAD

**Issue by Latekek** [chiyadev/MudaeFarm#119]
can i set a kakera claim delay? lately the discord i'm playing on set the kakera claiming delay to 4 seconds so that means the bot can't claim anymore. Is there a way to set a kakera claim delay?

**Comment by phosphene47** [comment]
You're looking for [kakera_delay_seconds](https://github.com/chiyadev/MudaeFarm#configuration).

**Comment by Latekek** [comment]
awww man i'm retarded today, thank you
