### ISSUE TITLE
presence update

### ISSUE THREAD

**Issue by Latekek** [chiyadev/MudaeFarm#120]
Since today the bot spamms presence update user =  in the console thing and doesn't claim. How do i fix? 
![Screenshot_1](https://user-images.githubusercontent.com/62397695/82233252-059ee200-9930-11ea-8d84-867bf54d34fd.png)

**Comment by phosphene47** [comment]
`PRESENCE_UPDATE` by itself does not necessarily indicate bugs, but I'm not sure about not claiming. I can't determine anything useful given the logs, and nothing in MudaeFarm's source code has changed in months, so it is likely that Discord is acting faulty.

**Comment by Latekek** [comment]
well i reseted my pc and now it works fine again

**Comment by phosphene47** [comment]
Feel free to tell me to reopen this issue if it occurs again. I have no clue about what causes this however.
