### ISSUE TITLE
Could not react with heart emote.

### ISSUE THREAD

**Issue by Cowbama** [chiyadev/MudaeFarm#126]
Hi, im having this problem. Half of the claims get this error, other half claims right.
https://imgur.com/a/eXgEdnK

i "enable_custom_emotes": true  after last time i got this error but got it agaian after. 

Thanks for any help, really love your work.
there are my settings:

General
{
  "enabled": true,
  "fallback_status": "Idle",
  "state_update_command": ""
}
Claiming
{
  "enabled": true,
  "delay_seconds": 0.2,
  "kakera_delay_seconds": 0.2,
  "kakera_targets": [
    "Purple",
    "Blue",
    "Teal",
    "Green",
    "Yellow",
    "Orange",
    "Red",
    "Rainbow"
  ],
  "enable_custom_emotes": true
}
Rolling
{
  "enabled": true,
  "command": "$w",
  "roll_with_no_claim": false,
  "daily_kakera_enabled": false,
  "daily_kakera_command": "$dk",
  "daily_kakera_then_state_update": true,
  "typing_delay_seconds": 0.3,
  "interval_override_minutes": null
}
Miscellaneous
{
  "auto_update": true
}

**Comment by phosphene47** [comment]
Can you try [v4](https://github.com/chiyadev/MudaeFarm/releases/tag/v4.0.0)? If this problem still persists, we can reopen this issue.
