### ISSUE TITLE
bot doesn't claim

### ISSUE THREAD

**Issue by Latekek** [chiyadev/MudaeFarm#129]
the bot doesn't claim? i have the char in wished chars but it didn't claim : (
![image](https://user-images.githubusercontent.com/62397695/83328629-a5d7fd80-a284-11ea-8e40-75e3ee3ad250.png)

**Comment by phosphene47** [comment]
Can you send a screenshot of the character wishlist channel?

**Comment by Latekek** [comment]
ofc 
![image](https://user-images.githubusercontent.com/62397695/83328705-4c240300-a285-11ea-93bd-36750daabe31.png)

**Comment by Latekek** [comment]
maybe something is wrong inhere but the bot did say that i didn't wish the char so i don't think so
![image](https://user-images.githubusercontent.com/62397695/83328817-3400b380-a286-11ea-82d5-de40959f94f0.png)

**Comment by phosphene47** [comment]
Thanks for your quick reports. It really helps a lot! [v4.0.1](https://github.com/chiyadev/MudaeFarm/releases/tag/v4.0.1).

**Comment by Latekek** [comment]
Np <3

**Comment by Latekek** [comment]
yeah it works now :3
