### ISSUE TITLE
You need to look for the file "MudaeFarm.exe".

### ISSUE THREAD

**Issue by Cowbama** [chiyadev/MudaeFarm#130]
Only have MudaeFarm.sln in the folder of 4.0. Am i missing something?

**Comment by phosphene47** [comment]
Did you download [win-x64.zip](https://github.com/chiyadev/MudaeFarm/releases/download/v4.0.1/win-x64.zip)? You might have downloaded the source code zip instead.

**Comment by Cowbama** [comment]
Works like a charm! Thanks looks great!
