### ISSUE TITLE
Stops rolling before everything is finished

### ISSUE THREAD

**Issue by ssj4maiko** [chiyadev/MudaeFarm#131]
I can understand the reason why not using $tu anymore, so this is what is happening to me:
I have 29 rolls (13 from bot, 6 from badges, 10 from kakera loots), but 2 times already, it rolled up to 27 and stops

```
info: MudaeFarm.MudaeRoller[0]
      Sent roll 26 of batch 2 in channel 'rolling' (***).
warn: MudaeFarm.MudaeRoller[0]
      Could not handle Mudae response for command '$wb auto'. Assuming a sane default of 5 rolls per hour (27 right now). Response: ***, 2 uses left.
info: MudaeFarm.MudaeRoller[0]
      Preemptively finished roll 27 of batch 2 in channel 'rolling' (***). Next batch in an hour.
```

There have been also issues regarding claiming, both kakera and characters. The list is the same as before, so I keep multiple names per line in a single post, on both character and anime, but I guess these others may have already been reported.

**Comment by phosphene47** [comment]
I can confirm that autorolling stops prematurely.

I forgot about MudaeFarm having supported multiple characters in a single message in #wished-characters.

Will fix in next release.
