### ISSUE TITLE
Copy Mudae wishlist to MudaeFarm wishlist

### ISSUE THREAD

**Issue by Latekek** [chiyadev/MudaeFarm#133]
my recommendation is that when you put your id in wishlist users the bot writes the chars from your wl into wished chars so you can make your wishlist private again its just annoying when you change your whole wishlist and you need to write 20 chars down again. some player copy your wishlist to get chars that you want to get chars that you don't want to trade so it would be a nice option in imo (sorry for bad english)

**Comment by phosphene47** [comment]
Can't this be done manually? `#wished-characters` supports specifying multiple characters in one message, one per line.

**Comment by Latekek** [comment]
oh. i didn't know that, i thought you need every char in a single message. yeah thats why faster, sorry
