### ISSUE TITLE
kakera not claiming ?

### ISSUE THREAD

**Issue by Latekek** [chiyadev/MudaeFarm#135]
yes yes it's me again so i noticed rn that the bot doesn't claim kakera that i want him to claim? so yes this are my settings maybe something is messed up but i don't think so
![image](https://user-images.githubusercontent.com/62397695/83341012-fda35280-a2de-11ea-94af-faddee9bea2f.png)

**Comment by Restiasan** [comment]
Already tried using ignore cooldown "true"?

**Comment by Latekek** [comment]
it claims char with ignore cooldown false so i think it will change nothing, just my theorie

**Comment by phosphene47** [comment]
Your `kakera_targets` are only red and rainbow. Also, your `kakera_delay_seconds` is 8 seconds. Are you sure these are intentional? I don't think Mudae allows you to claim kakera after a long delay.

**Comment by Latekek** [comment]
Yeah I just want red and rainbow because the other ones are useless imo, also 8 seconds are right cause my discord plays on kakerasnipe 2 (need to wait 8 ske to snipe kakera)

**Comment by phosphene47** [comment]
Kakera is definitely working on my end. Can you send a screenshot of the roll and the log file?

**Comment by Latekek** [comment]
i can't find it

**Comment by Latekek** [comment]
there
![Screenshot_2](https://user-images.githubusercontent.com/62397695/83351370-80f68f80-a343-11ea-94c0-bbd58ac5dbca.png)

![Screenshot_1](https://user-images.githubusercontent.com/62397695/83351369-805df900-a343-11ea-98d4-18cf06b8b756.png)

**Comment by Latekek** [comment]
there
![Screenshot_2](https://user-images.githubusercontent.com/62397695/83351397-c7e48500-a343-11ea-9022-14cadf3eaab9.png)
![Screenshot_3](https://user-images.githubusercontent.com/62397695/83351400-c87d1b80-a343-11ea-9d0b-cb1390e00fa8.png)
