### ISSUE TITLE
multi accounts 

### ISSUE THREAD

**Issue by 7angels** [chiyadev/MudaeFarm#146]
my server is quite friendly and a lot of us have multiple accounts to play on the same server, I wonder if it was possible to have the bot run no both accounts, I've tried running multiple instances using two different file locations but that does not work

**Comment by phosphene47** [comment]
Edit your profiles.json file at `%localappdata%` like this:

```json
{
  "first account name": "first account token",
  "second account name": "second account token"
}
```

and update the channel topic of #information in your configuration server to match the profile name.

This is all described in the configuration guide.
