### ISSUE TITLE
[Request] Claim notification

### ISSUE THREAD

**Issue by Hax-san** [chiyadev/MudaeFarm#148]
Simply as that, when the autobot claims something (kakera or character) it will make a sound or display a windows notification (by choice if possible), preventing to claim something without knowledge (in case one character in the configuration wishlist isn't in the actual Mudae wishlist or wished via wishk).

**Comment by phosphene47** [comment]
MudaeFarm is cross-platform, so this will be a Windows-specific feature if implemented.

**Comment by zhaobenny** [comment]
I think I got notifications working when a character is claimed, on my fork. 
I just need to test some more to see if it works properly, do you mind contributors to this issue?

**Comment by phosphene47** [comment]
@zhaobenny You're welcome to contribute!
