### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Latekek** [chiyadev/MudaeFarm#149]
does the bot claim both reactions  (custom and normal heart emotes) or just customs when i activate "enable_custom_emotes"?

**Comment by phosphene47** [comment]
Set `enable_custom_reactions` true to allow claiming using custom emotes. Otherwise, it will only allow heart emoji.

**Comment by Latekek** [comment]
ok another question, does the bot claim every hour or every time he sees a wish? i want to go to sleep and let the bot still run but idk if he claims everything or just every hour

**Comment by phosphene47** [comment]
It claims everything in the wishlist if you're not on cooldown.

**Comment by Latekek** [comment]
my question is if the bot knows that you're not on cooldown

**Comment by phosphene47** [comment]
**It does**. Otherwise I would not have said what I said.

**Comment by Latekek** [comment]
ok thx
