### ISSUE TITLE
Cannot start new MudaeFarm

### ISSUE THREAD

**Issue by pinyo6** [chiyadev/MudaeFarm#153]
Everytime i try to start the new MudaeFarm i get this and am unable to do anything, i have no idea whats going on but ill show a screenshot.
https://user-images.githubusercontent.com/63222850/84570762-e1211300-add2-11ea-81c0-173bb7bd2a02.jpg

**Comment by phosphene47** [comment]
It looks like your auth token had expired. Can you try editing `profiles.json` in the folder `%localappdata%\MudaeFarm` and replace your old token with a new one?

**Comment by pinyo6** [comment]
Ah yes i am now able to use the new version, thanks alot.
