### ISSUE TITLE
bot ignored a wished character

### ISSUE THREAD

**Issue by edu7213** [chiyadev/MudaeFarm#154]
![image](https://user-images.githubusercontent.com/66887277/84579163-211bd200-ada2-11ea-908d-087ca6d47987.png)
 i follow the instructions and the bot ignored (in this case) the rem, i dont know if i put it wrong or if is a problem with the code

**Comment by KingJackFrost** [comment]
I can answer this. The bot scans for the name, so you could opt to put `Raphtalia` instead of `Raphtalia (Tate no Yuusha no Nariagari)`

For your case, you spelled it as `Ram,` and not `Rem.`

**Comment by phosphene47** [comment]
You need to put the character names without the code block.

![image](https://user-images.githubusercontent.com/27663662/84582595-3e4bb180-ae31-11ea-9b91-8f3b00e9fcdd.png)

@KingJackFrost `Raphtalia (Tate no Yuusha no Nariagari)` is correct.
