### ISSUE TITLE
Bot breaks and spams chat

### ISSUE THREAD

**Issue by angeeree** [chiyadev/MudaeFarm#162]
At some point the farm falls apart and fails to parse anything Mudaebot sends, even normal rolls. It seems insane to me that MudaeFarm would try every ~30 seconds indefinitely and create hundreds of messages. Unsanitized logs below, timestamp is 2020-06-19T21:59:41.2842398-05:00
[log_2020-06-19 06.22.24Z-20200619.txt](https://github.com/chiyadev/MudaeFarm/files/4807768/log_2020-06-19.06.22.24Z-20200619.txt)
EDIT: I just realized these logs aren't verbose. Given it's been happening every night, I'll have some soon

**Comment by phosphene47** [comment]
Thank you for providing the logs which really helps me determine the cause. It seems like Disqord had a connection error but failed to reconnect, and MudaeFarm didn't anticipate such circumstance. I can't fix it, but I'll push a workaround in the next release to prevent this.
