### ISSUE TITLE
Mudae.dll trojan?

### ISSUE THREAD

**Issue by patato546** [chiyadev/MudaeFarm#165]
![trojan](https://user-images.githubusercontent.com/67236264/85230406-b85ad800-b3e7-11ea-9b48-ae8bdc3e1b1c.JPG)

Hi,

I was running the bot and it was all ok. Then after a windows security scan it qurantined mudae.dll for a trojan. I deleted the previous files and redownloaded the bot and have the same error. Should I remove the mudae.dll from the filter list?

**Comment by joshoea** [comment]
I mean what else can you do? You have to allow it to work. It happened to me. First allow it to run and then if it doesn't open (which is what happened to me), download it again in the same folder/location you downloaded it before and run it. Works flawlessly after.

**Comment by patato546** [comment]
> 
> 
> I mean what else can you do? You have to allow it to work. It happened to me. First allow it to run and then if it doesn't open (which is what happened to me), download it again in the same folder/location you downloaded it before and run it. Works flawlessly after.

Yeah, I had the same thought process. In the end it let it through, just wanted to know if other people had the same issue.

**Comment by phosphene47** [comment]
I can't control Windows Defender alerting false positives. I can guarantee you MudaeFarm is legitimate software, but if you still have doubts, MudaeFarm's source code is completely open for anyone to compile and examine!

Leaving this issue open for visibility.

**Comment by phosphene47** [comment]
This is VirusTotal's [scan results](https://www.virustotal.com/gui/file/c0bbb84943240696bb35b40ef68e7edd5696d4f256e69596f253b9b0607adbbf/detection) by the way.

![image](https://user-images.githubusercontent.com/27663662/85273795-6dad8e80-b4c1-11ea-83b0-37d1f835969c.png)

**Comment by patato546** [comment]
> 
> 
> This is VirusTotal's [scan results](https://www.virustotal.com/gui/file/c0bbb84943240696bb35b40ef68e7edd5696d4f256e69596f253b9b0607adbbf/detection) by the way.
> 
> ![image](https://user-images.githubusercontent.com/27663662/85273795-6dad8e80-b4c1-11ea-83b0-37d1f835969c.png)

Thank you for taking your time to respond.

**Comment by joshoea** [comment]
Had an issue with AVG on my built pc. AVG antivirus wouldn't even give me a pop up that it was  "virus" I simply couldn't even open the win64 zip. In the end I uninstalled AVG antivirus.

**Comment by phosphene47** [comment]
I don't think this happens anymore as new updates are released. Tell me to reopen if this still occurs.

**Comment by joshoea** [comment]
This was when I first downloaded it. I couldn't open the zip to download it for some reason. I have 2 others windows 10 and it didnt happen on those. Its weird because different scnearios happen with antivirus and windows security on all 3 laptops/pcs
