### ISSUE TITLE
Mudaebot not rolling?

### ISSUE THREAD

**Issue by PureAnarchy** [chiyadev/MudaeFarm#167]
Hi, I think i have set up the bot correctly but it is not rolling like it is supposed to. Here is the current settings: 
 "fallback_status": "idle",
  "reply_typing_cpm": 190.0,
  "auto_update": true
}
Claiming
{
  "enabled": true,
  "delay_seconds": 0.2,
  "ignore_cooldown": false,
  "kakera_delay_seconds": 0.2,
  "kakera_ignore_cooldown": false,
  "kakera_targets": [
    "Purple",
    "Blue",
    "Teal",
    "Green",
    "Yellow",
    "Orange",
    "Red",
    "Rainbow"
  ],
  "enable_custom_emotes": false
}
Rolling
{
  "enabled": true,
  "command": "$m",
  "daily_kakera_enabled": false,
  "daily_kakera_command": "$dk",
  "typing_delay_seconds": 2.0,
  "interval_seconds": 0.1
}

Is there any recommended settings that I should change? 
Thanks.

**Comment by joshoea** [comment]
There is no settings. It must be you are using it wrong. You have to keep the cmd prompt window open. For now, restart discord and reopen mudaefarm.exe. This should make it execute $m. Perhaps it recongizes you are on cooldown.

**Comment by PureAnarchy** [comment]
> 
> 
> There is no settings wrong. It must be you are using it wrong. You have to keep the cmd prompt window open. For now, restart discord and reopen mudaefarm.exe. This should make it execute $m. Perhaps it recongizes you are on cooldown.

Thank you so much, you helped me out a ton. I realized i didnt have the cmd open, hah

**Comment by joshoea** [comment]
Yeah no problem. I thought so. Just a pointer, if you are using a laptop and want mudae bot rolling all the time (especially in a private server) you can change power options so the laptop doesn't sleep when lid is closed. But obviously in a big public server don't do this or you will be banned.

**Comment by PureAnarchy** [comment]
Got it, thanks.

**Comment by phosphene47** [comment]
@joshoea Thanks for helping out.
