### ISSUE TITLE
MudaeFarm does not launch

### ISSUE THREAD

**Issue by Yoluxios** [chiyadev/MudaeFarm#169]
Hello,
Here is what the software shows me when I launch it.
I have tried to uninstall it several times but the error still appears ...
![Screenshot_4](https://user-images.githubusercontent.com/67338607/85442153-217d4f80-b590-11ea-885e-91dfadd83b85.png)

**Comment by phosphene47** [comment]
Please see https://github.com/chiyadev/MudaeFarm/issues/164.
