### ISSUE TITLE
2 Profiles doesn't work

### ISSUE THREAD

**Issue by joshoea** [chiyadev/MudaeFarm#172]
The only way to use two profiles for me in %localappdata%\MudaeFarm\profiles.json is to delete the first one and rewrite. 2 profiles resulsts in app crash of MudaeFarm.exe

**Comment by joshoea** [comment]
Those who are curious; DO NOT FORGET THE COMMA IN BETWEEN EACH PROFILE LMFAO

**Comment by phosphene47** [comment]
Please learn how to write a JSON file before creating issues such as this.
