### ISSUE TITLE
Is 2 error the firts is the bot not roll the full amount of rolls and the 2 i have no idea what is

### ISSUE THREAD

**Issue by Fpsroxas** [chiyadev/MudaeFarm#174]
the 2 error are in the same log
[log_2020-06-25 16.17.51Z-20200625.txt](https://github.com/chiyadev/MudaeFarm/files/4833635/log_2020-06-25.16.17.51Z-20200625.txt)

**Comment by phosphene47** [comment]
Please write the title in comprehensible English in the future.

As for the errors, restarting MudaeFarm should fix them.
