### ISSUE TITLE
Could not reload configuration channel 'wished-characters'

### ISSUE THREAD

**Issue by yud54** [chiyadev/MudaeFarm#178]
why did i get this problem? Is my writing wrong in the wished-character channel?
![wished character 0](https://user-images.githubusercontent.com/67561171/85958755-1b3d0800-b9c2-11ea-89fc-c5183fa8481f.png)
![wished character 1](https://user-images.githubusercontent.com/67561171/85958762-26903380-b9c2-11ea-8cf7-6a68e21d2798.png)

**Comment by phosphene47** [comment]
Please re-read the [configuration guide](https://github.com/chiyadev/MudaeFarm#wished-characters) and try again. If you want to use the JSON syntax, you need to send the JSON string without any formatting.
