### ISSUE TITLE
run multiple program mudaefarm

### ISSUE THREAD

**Issue by yud54** [chiyadev/MudaeFarm#180]
in 1 pc whether it can run 3 young farming programs for 3 accounts? if that can be, how is it going. Thank you in advance

**Comment by phosphene47** [comment]
[I already answered your question](https://github.com/chiyadev/MudaeFarm/issues/152#issuecomment-651606069).

**Comment by joshoea** [comment]
dont need multiple compuiters. You only need one pc to run multiple accounts.
