### ISSUE TITLE
New Feature: $p for the pokemon roulette.

### ISSUE THREAD

**Issue by joshoea** [chiyadev/MudaeFarm#183]
This isn't just a waifu roulette but rather an "auto mudaefarm". $pokemon is another command just for pokemon and It wouldnt be super hard to code. considering its just one command  $P

**Comment by phosphene47** [comment]
MudaeFarm will not be adding support for Mudae games other than the waifu roulette.

Be creative. How about creating a new profile, setting the roll command to `$p` and adjusting `interval_seconds`?

**Comment by joshoea** [comment]
smart i never thought of that
