### ISSUE TITLE
multiple profiles not working?

### ISSUE THREAD

**Issue by Yashirowo** [chiyadev/MudaeFarm#186]
i tried to play with 2 profiles and added "user B" : "token" under "user A" but it doesn't work and the bot  closes everytime how do i fix?

**Comment by joshoea** [comment]
Use commas🤔🤔🤔

**Comment by Yashirowo** [comment]
i did

**Comment by joshoea** [comment]
what i thought

**Comment by Yashirowo** [comment]
nah it wasn't because of commas bro

**Comment by joshoea** [comment]
What was it?🤔

**Comment by Yashirowo** [comment]
1 space too much under user a xd

**Comment by phosphene47** [comment]
This is not an issue with MudaeFarm. Please learn how to write a JSON file.
