### ISSUE TITLE
Bot not verifying channel id.

### ISSUE THREAD

**Issue by kpierce11** [chiyadev/MudaeFarm#188]
I have confirmed the channel ID I am trying to monitor multiple times and it doesn't replace the message with a tagged channel. I'm not sure how to verify if the bot is working or not for me at this point but at the very least that part isn't.

**Comment by phosphene47** [comment]
You close this issue. Is it working now?

**Comment by joshoea** [comment]
I actually had a similar issue, but I think it only works after you
reinstall everything. I've done this with a profile which I downloaded for
a week without doing anything and then I put in the channel ID with nothing
happening. Then I just redownloaded. I think the Id thing only works a
little after you install it. Not sure though
