### ISSUE TITLE
Bot reacting to $im command which shouldn't be the case

### ISSUE THREAD

**Issue by sofa2000hatem** [chiyadev/MudaeFarm#189]
the $im search command is treated the same as the $wa command. So, when I search for the character it gets reacted for the first reaction that corresponds to it.
Would suggest if you make a channel to add in the custom heart emojis that are used or exclude certain emojis so that it avoids reacting to unnecessary searching .
![image](https://user-images.githubusercontent.com/49553755/87267994-d5bd2680-c4fb-11ea-99cf-bb4988a46d5e.png)

**Comment by phosphene47** [comment]
Have you [enabled](https://github.com/chiyadev/MudaeFarm/releases/tag/v4.0.4) `bypass_im_check_bug_152`? If so, try disabling it.

**Comment by phosphene47** [comment]
On another note, this issue is caused by the same reason as https://github.com/chiyadev/MudaeFarm/issues/152.

**Comment by sofa2000hatem** [comment]
Ok it works now I should've disabled the bypass

**Comment by Biop6** [comment]
when disabling bypass_im_check_bug_152 stops recognizing the waifu in the roll,
