### ISSUE TITLE
Kakera_ignore_cooldown doesn't work?

### ISSUE THREAD

**Issue by RedCon329** [chiyadev/MudaeFarm#191]
![image](https://user-images.githubusercontent.com/68579011/88281995-409c0800-cd1b-11ea-9268-a8774716554c.png)
![image](https://user-images.githubusercontent.com/68579011/88282272-ce77f300-cd1b-11ea-9a07-e080e7382b31.png)

so yeah the title says it all, the bot stills claims the kakera even though the kakera_ignore_cooldown is set to false. how to fix?

**Comment by RedCon329** [comment]
![image](https://user-images.githubusercontent.com/68579011/88635783-ad801b00-d0ea-11ea-8b53-492aa927f503.png)

also the script still seems to claim purple kakera even though i deactivated purple kakera claiming?

so far the kakera script is still buggy.. need fix

**Comment by phosphene47** [comment]
Thanks for the detailed issue. Since this is a duplicate, I will close this one in favor of https://github.com/chiyadev/MudaeFarm/issues/161.
