### ISSUE TITLE
how do i start up the bot?

### ISSUE THREAD

**Issue by ichigo270** [chiyadev/MudaeFarm#193]
Im pretty sure i did everything i needed to do but i have no idea how to start up the bot please help

**Comment by phosphene47** [comment]
After downloading and extracting [win-x64.zip](https://github.com/chiyadev/MudaeFarm/releases/tag/v4.0.4.1) open MudaeFarm.exe in the folder.

**Comment by ichigo270** [comment]
yes and after i put my discord pin in, is there a command that i put in to start everything up ?

**Comment by phosphene47** [comment]
I don't know what a Discord pin is, but you're probably talking about your token. Yes, after inputting your token MudaeFarm will create a configuration server and begin listening to messages. You need to leave the console open. This is all described in the configuration guide.

**Comment by ichigo270** [comment]
oops yes hehe i meant pin lol thank you i will try this rn

**Comment by bigweld3120938** [comment]
my console says it has loaded all of the configuration but nothing is happening, what do i do after my console is loaded  and i set up everything in my created discord?

**Comment by phosphene47** [comment]
Then you're good to go. The bot is already listening to messages so leave the console open.

**Comment by bigweld3120938** [comment]
![fbf783cefe6d31eddae8896c80b438b0](https://user-images.githubusercontent.com/69020716/88986232-1774fd80-d26e-11ea-88aa-23aa78c35eca.png)
![bace831de951fcda377b527d092c8f34](https://user-images.githubusercontent.com/69020716/88986258-278cdd00-d26e-11ea-9479-cbb167c49ffa.png)
all this look good to you? 
im sorry i just dont know when itll start claiming and everything lol

**Comment by bigweld3120938** [comment]
![mudae](https://user-images.githubusercontent.com/69020716/88986423-a124cb00-d26e-11ea-8486-307d8c40a79d.png)
![mudae 2](https://user-images.githubusercontent.com/69020716/88986424-a255f800-d26e-11ea-9d64-a054968ff870.png)
does this look all good to you? 
im sorry im just having a hard time understanding when the bot is going to start claiming and rolling

**Comment by phosphene47** [comment]
Yes. If you really want to test the bot, put a `*` in the character wishlist to make it claim everything. You could also start it with a --verbose CLI option.

**Comment by bigweld3120938** [comment]
whats a CLI option?

**Comment by bigweld3120938** [comment]
yeah its not starting could you possibly show me how it works?

**Comment by phosphene47** [comment]
As I said, the bot is working as long as the console window is open, even if it's not displaying any logs. If you want to test that it's listening to messages, put a `*` in the character wishlist and the bot should claim the first character it sees in the bot channels you've configured. Re-read the configuration guide that explicitly explains everything and try again.

On the other hand, if it's not claiming when it should definitely have, please create a new issue and I'll investigate it.
