### ISSUE TITLE
#Wished Characters 

### ISSUE THREAD

**Issue by rocknbigc** [chiyadev/MudaeFarm#197]
Not sure if my wished characters are set up properly
![44f4ded5913c384d8ebdc0e136fb90b4](https://user-images.githubusercontent.com/69224705/89358486-13d7e100-d689-11ea-8993-9983f2941154.png)

**Comment by phosphene47** [comment]
That looks correct. Make sure you don't forget to put series disambiguation when applicable, like `Nami (what anime?)`. Or use `Nami *` if you don't know.
