### ISSUE TITLE
How can I tell if the characters in #wished-character are properly set up?

### ISSUE THREAD

**Issue by Sabagabu** [chiyadev/MudaeFarm#212]
I cannot tell because there is no checkmark of any sort so I want to ask if theres a way to verify that the wished characters actually set up properly? also, I set up the notify for kakera but didnt get any notification for kakera claim. please help me understand this better! thank you

**Comment by Sabagabu** [comment]
> I cannot tell because there is no checkmark of any sort so I want to ask if theres a way to verify that the wished characters actually set up properly? also, I set up the notify for kakera but didnt get any notification for kakera claim. please help me understand this better! thank you

also, how do i set up timer intervals? in my server it is 18 rolls per hour

**Comment by phosphene47** [comment]
If you want to see how the bot interprets your wishlist channel, you can [run the bot with verbose logging](https://github.com/chiyadev/MudaeFarm#reporting-bugs) which should show you exactly what configurations are loaded.

> also, how do i set up timer intervals? in my server it is 18 rolls per hour

The bot rolls until there are no more rolls i.e. Mudae says you don't have any more rolls.
