### ISSUE TITLE
I cant change my token?

### ISSUE THREAD

**Issue by himitoes** [chiyadev/MudaeFarm#217]
So as i was downloading MudaeFarm, i got to putting in my token. Apparently i accidently did something and messed up my id, so i did as the error screen sad and went to profiles.json. However, once there, i am unable to edit my token. Is there anything specific i have to do/open it with?

**Comment by Fpsroxas** [comment]
simply delete the profiles.json and run the bot, this will make the bot ask to put the token again

**Comment by phosphene47** [comment]
You can delete it, that will certainly work. If you can't edit the `.json` you can also temporarily change it to `.txt` and open it with notepad.
