### ISSUE TITLE
Inviting the bot to my channel & changing claims (more of a question)

### ISSUE THREAD

**Issue by himitoes** [chiyadev/MudaeFarm#219]
I'm again confused/having issues. I've sent the channel ID for my bot channel to the #bot-channels, however Mudaefarm doesn't appear in my server. Along with that, is there anything i have to put before i type things in? For instance, would I have to put $ before i type in what's enabled and what's not?

**Comment by himitoes** [comment]
update; got the bot into the server, and everything seems to be working well

**Comment by phosphene47** [comment]
Good to hear that it's working. MudaeFarm isn't a traditional bot where you enter commands with a prefix, so you should refer to the configuration guide.
