### ISSUE TITLE
Question -  Delete mudaefarm fullclean

### ISSUE THREAD

**Issue by Biop6** [chiyadev/MudaeFarm#220]
Is it possible to delete the mudaefarm entirely from the computer and also, any information in the discord account that some kind of selfbot was used?
I ask, because I use the bot on a private server where only I am on it, but I was wanting to play on other servers without mudaefarm.
And I looked at cases where they requested remote access to check if the person uses or has already used it, to set a BAN, as I intend NOT TO USE, I would like to completely clean my computer and disagree with any record of usage of mudaefarm

**Comment by phosphene47** [comment]
The only place MudaeFarm saves information on disk is the folder `%localappdata%\MudaeFarm`. This folder contains `profiles.json` which contains your token. You can delete this folder and you should be good to go.

Personally I don't think remote access is effective since you can download it again or use a VM... but that's irrelevant.

**Comment by Biop6** [comment]
And in the discord account, is there any information that selfbot has been used in the account?

**Comment by Biop6** [comment]
And in the discord account, is there any information that selfbot has been used in the account?

**Comment by phosphene47** [comment]
You can delete the configuration server that MudaeFarm creates. There should be nothing other than that.

**Comment by Biop6** [comment]
nothing about webhook or even an authorized dev that I can link my account to the bot or that github?

**Comment by phosphene47** [comment]
If you linked your discord account to your github you can unlink it, but this is not within the scope of MudaeFarm. Your account isn't "linked" to MudaeFarm. MudaeFarm doesn't use any webhooks either.
