### ISSUE TITLE
Suggestion: Way to disable state_update_command 

### ISSUE THREAD

**Issue by Hcopson** [chiyadev/MudaeFarm#35]
Wondering if there is a way to disable it completely

**Comment by phosphene47** [comment]
`state_update_command` is necessary for the bot to determine:

- whether claiming is on cooldown
- rolling interval and how many rolls you have left
- daily kakera reset time

What do you expect to happen if you disable it?

**Comment by Hcopson** [comment]
It seems a bit fishy to have the bot do $tu right before each roll time to other people (If someone doesn't want to be found using a selfbot that is). The older versions of Mudaefarm was discreet in that way. I roll and reset kakera manually, so I didn't think about those things so that was my bad. 

Would there be a way to do $mu instead, and the bot uses that information to autoclaim?

**Comment by code-moe** [comment]
hello.. I'd like to ask the same.. Is it possible just to activate autoclaim feature by itself?
and disable state_update_command > whether claiming is on cooldown
how about just claiming Top 200, the program doesnt need to know whether claiming is on cooldown or not.. just when the characters in wishlist appear it will autoclaim them (by clicking heart)

**Comment by phosphene47** [comment]
> disable state_update_command > whether claiming is on cooldown

This does not make sense. As I said, without `state_update_update` the bot has no way of determining whether you're on cooldown or not.

If `state_update_command` can be disabled, the bot will attempt to autoclaim regardless of cooldown. 

> how about just claiming Top 200, the program doesnt need to know whether claiming is on cooldown or not

That's not how it works, and is a completely different feature.

**Comment by phosphene47** [comment]
[v2.3](https://github.com/chiyadev/MudaeFarm/releases/tag/v2.3)
