### ISSUE TITLE
AutoRoller/Claimer not working as expected 

### ISSUE THREAD

**Issue by Ridleh** [chiyadev/MudaeFarm#37]
When rolling a character, MudaeFarm bot will correctly identify the rolled character as someone in my wish list. However, the bot will not claim the character, printing the error "{guild} {message.Channel}: Found character '{character}' but cannot claim it due to cooldown.". This is printed even after confirming I am eligible to claim a character. 

wished characters list: 
a*
b*
c*
*

Second, After correctly linking a channel, and setting autoroll to true, I am unable to get the auto roll command to work. I am assuming i type "$w", the default command, in the channel i linked, however this does not work. Though I have a feeling these problems are leaning towards human error on my part, so any advice is appreciated.

**Comment by phosphene47** [comment]
Can you send `$tu` in the bot channel and post what the console prints?

**Comment by Ridleh** [comment]
typing $tu in the channel i linked gives me: 
<My_Username>, you can claim right now! The next claim reset is in 33 min.
You have 9 rolls left.
Next rolls reset in 33 min.
Next $daily reset in 12h 46 min.

If you meant typing the same command inside the bot-commands channel in the MudaeFarm server i get: 
[dbug] Configuration channel '$bot-channels' reloaded.

Im not sure if this would help, but I currently use Mudae in two servers. the number of rolls and the time to claim are different in each

**Comment by phosphene47** [comment]
Looks like you don't have any Kakera. Try doing `$dk` to get some Kakera and the bot should start working.

This is a limitation of the bot.

**Comment by Ridleh** [comment]
typing $dk and restarting the application worked. Upon initial launch the bot is able to successfully roll and claim a character. However it only rolls once, even after setting typing_delay_settings to 0.0, will investigate why.

**Comment by phosphene47** [comment]
If it had already claimed, you're on cooldown. The bot will not attempt to claim any rolls during cooldown.

**Comment by Ridleh** [comment]
That makes sense, thank you very much

**Comment by Ridleh** [comment]
One last thing, sorry for reopening. Do I have to add my wished characters and animes into a single message, or can i add them using individual messages?

**Comment by phosphene47** [comment]
You have to use individual messages. You cannot use a single message.
