### ISSUE TITLE
Delays when running the program

### ISSUE THREAD

**Issue by notanonymous12** [chiyadev/MudaeFarm#4]
I'm not sure if my program is running correctly in the first place, but it did auto claim for me. I noticed it had fail errors as well, but I ignored it. 
For some reason, I'm having a delay when running the program. It used to show ignored character [] not wished instantly when someone did $w, but not there's a delay. 
When running the program, it shows 
```
warn: MudaeFarm.Program[0]
          Failed to resume previous session
warn: MudaeFarm.Program[0]
          Unknown Dispatch[SESSIONS_REPLACE]
```
very frequently.

When doing dotnet build, I noticed there's a Restore Completed in xx.x sec . 

I've tried redownloading, but it still does that.

**Comment by notanonymous12** [comment]
![image](https://user-images.githubusercontent.com/49496975/55909260-60dc9d80-5b90-11e9-9e54-199f32a887f4.png)
This is the error that comes up, but I usually ignore it.

**Comment by phosphene47** [comment]
The permission error is a `Discord.Net` error and not directly related to MudaeFarm.
The session error is most likely due to Discord servers being overloaded at the time you connected.

I'm not sure about the heartbeat error, but it's not relevant to MudaeFarm either.

**Comment by notanonymous12** [comment]
> The permission error is a `Discord.Net` error and not directly related to MudaeFarm.
> The session error is most likely due to Discord servers being overloaded at the time you connected.
> 
> I'm not sure about the heartbeat error, but it's not relevant to MudaeFarm either.

I do know that I follow all the steps correctly, but it doesn't run smoothly most of the time for me. It runs great when it works. Sometimes it sits there after it says ready and doesn't do anything and then I get the premission error. Other times I get delays and then after a while, it gets errored out. The delays are basically the characters that popped up a while ago and are too late for the bot to react in case something does get wished. It could be like a 3-15 min delay before it breaks and tries to restart but sits there after restarting.

**Comment by phosphene47** [comment]
I understand. Unfortunately I can't help with issues related to `Discord.Net` library.

My best guess is that there was a change in Discord's API which the outdated version of `Discord.Net` isn't aware of. MudaeFarm deploys an outdated version because newer versions of the library disallow selfbots from logging in entirely.

You might try to open an issue at `Discord.Net`'s repository, but I highly doubt anyone will investigate in this issue, let alone leave it open.
