### ISSUE TITLE
Unhandled RateLimitedException causes MudaeStateManager to fail

### ISSUE THREAD

**Issue by Fpsroxas** [chiyadev/MudaeFarm#42]
I'm saying about a 1 hour difference between dropping a character and the bot recognizing it

**Comment by phosphene47** [comment]
Logs? Message history? Configuration? Anything to be helpful?

**Comment by Fpsroxas** [comment]
![image](https://user-images.githubusercontent.com/45643566/66220392-4e58a200-e6a3-11e9-8de6-70871f78e5c7.png)
not sure if that numbers are safe to be visible so I hide them

**Comment by Fpsroxas** [comment]
![image](https://user-images.githubusercontent.com/45643566/66220476-7a742300-e6a3-11e9-9c23-832777176111.png)
Configuration

**Comment by Fpsroxas** [comment]
to help the 12:29:22 is Glynda

**Comment by Fpsroxas** [comment]
after I send this a thing happen

**Comment by Fpsroxas** [comment]
![image](https://user-images.githubusercontent.com/45643566/66220865-36cde900-e6a4-11e9-9930-20ac6bea52fe.png)
