### ISSUE TITLE
Another Windows problem, dotnet

### ISSUE THREAD

**Issue by code-moe** [chiyadev/MudaeFarm#43]
Well I have another computer I want to run, but I think dotNET broke somehow..
Try searching google but can't find any real solution.. here's the screenshot
![mudaess](https://user-images.githubusercontent.com/54502171/66200050-55df7180-e6ca-11e9-9bd0-2309c0924b44.jpg)
here's the copy paste : https://pastebin.com/zVTE7g0D

**Comment by phosphene47** [comment]
This is an update problem. You can manually download the latest release as a workaround.

But before that, can you try installing [.NET 4.7](https://dotnet.microsoft.com/download/dotnet-framework/net47) if not already and try again?

Also, what build number is your Windows?

For dev: [relevant issue](https://github.com/dotnet/corefx/issues/26996)
