### ISSUE TITLE
Bot reacts with X reactions or 

### ISSUE THREAD

**Issue by rynhs** [chiyadev/MudaeFarm#49]
Bot reacts with X reactions or something like, 
Unknown User (VOICE_STATE_UPDATE User=204374437116641280 Guild=226368006115033091)

Can't get the bot to function, and putting a server ID in gives me the X or the error messages

**Comment by rynhs** [comment]
Is there a video tutorial?

**Comment by rynhs** [comment]
Got it to somehow work, and is connected to the channel, but I don't get a response when i add waifus to the wished characters, is this normal?

**Comment by phosphene47** [comment]
Do you have any kakera in that server? If not, try getting some with `$dk`.

I should mention this in the README.

**Comment by rynhs** [comment]
Thanks,

How do I speed up the $w?

**Comment by phosphene47** [comment]
`$w` from autorolling? It's determined automatically by the bot based on the number of rolls left.

You can override this with e.g. `"interval_override_minutes": 5` which is 5 minutes.

**Comment by phosphene47** [comment]
Feel free to reopen this issue if you have further questions.
