### ISSUE TITLE
How do you issue commands?

### ISSUE THREAD

**Issue by ovosile** [chiyadev/MudaeFarm#5]
I'm assuming you're allowed to create your own wishlist separate from mudae's bot, but I have no idea you're supposed to issue commands in order to add waifus to your wishlist and whatnot.

**Comment by phosphene47** [comment]
You can use commands in any channel. You might create a group chat consisting of only yourself, or a private server to use the commands.

**Comment by ovosile** [comment]
oh... so that's how it works... thanks for the advice.
