### ISSUE TITLE
Bug: Program keeps throwing HttpRequestException when disconnected from internet. 

### ISSUE THREAD

**Issue by Ridleh** [chiyadev/MudaeFarm#50]
School wifi cut off for about 3 minutes. Instead of printing "disconnected....connecting....etc..." like it usually would the program kept throwing an HttpRequestException and trying to restart. I think the root cause is the 'MudaeStateManager' module failing while not connecting to the internet. 

[_log - Copy.txt](https://github.com/chiyadev/MudaeFarm/files/3700008/_log.-.Copy.txt)
Log file for easier debug time :)

**Comment by Ridleh** [comment]
Also, towards the end you can see that whenever I do the $tu command, it prints the same info multiple times. I think its somehow related to the bug i mentioned above, but when I restarted the program it prints fine, so i don't think its worth submitting a new issue for

**Comment by phosphene47** [comment]
Seems like a Discord.Net issue if the `$tu` parsing event is triggered multiple times. However we might be able to do something about MudaeStateManager failing.
