### ISSUE TITLE
Possible bug : Bot ignoring characters it previously tried to claim

### ISSUE THREAD

**Issue by Ridleh** [chiyadev/MudaeFarm#51]
3 characters were rolled that the bot tried to claim. It was unable to due to the cooldown. When they appeared again (using the $im command ) the bot ignores them. Under normal circumstances, even if a character is drawn using the $im command, the bot will still try to claim.  These characters were selected because their anime was in my list of wished anime if that helps in any way. 
![piclog](https://user-images.githubusercontent.com/42791844/66367242-60676880-e961-11e9-84b1-a3abef33fc76.png)

**Comment by phosphene47** [comment]
Were those characters claimed later? If so, logs won't appear for them.

If not, can you post a screenshot of the roll of those characters?

**Comment by Ridleh** [comment]
![image](https://user-images.githubusercontent.com/42791844/66367570-b2f55480-e962-11e9-95c6-d2023d357529.png)
![image](https://user-images.githubusercontent.com/42791844/66367576-bd175300-e962-11e9-90de-cb9fa048380c.png)
![image](https://user-images.githubusercontent.com/42791844/66367587-c99bab80-e962-11e9-8e68-d68e1acaad2d.png)
![image](https://user-images.githubusercontent.com/42791844/66367595-d1f3e680-e962-11e9-9db8-bfabb2affdca.png)

**Comment by phosphene47** [comment]
The bot differentiates normal rolls and non-rolls by looking at the message footer ("Belongs to {somebody}" for claimed characters or "1/8" for `$im`). Non-rolls are **not logged**.

**Comment by Ridleh** [comment]
![image](https://user-images.githubusercontent.com/42791844/66368012-a83bbf00-e964-11e9-865c-80c1b9b75b5c.png)
![image](https://user-images.githubusercontent.com/42791844/66368024-ba1d6200-e964-11e9-832a-f76e3e7fe828.png)
![image](https://user-images.githubusercontent.com/42791844/66368031-c6a1ba80-e964-11e9-8236-1c6455ade257.png)
![image](https://user-images.githubusercontent.com/42791844/66368135-17b1ae80-e965-11e9-9766-0543127c2918.png)
![image](https://user-images.githubusercontent.com/42791844/66368041-cc979b80-e964-11e9-9296-e2f6a8a4b132.png)

But these characters are not claimed and they are logged when i do $im. Mei is claimed and is not logged like you said. Sorry for pic spam i do not know how to better format pics on github
