### ISSUE TITLE
MudaeFarm is not capturing channel messages from a server.

### ISSUE THREAD

**Issue by HiseTake** [chiyadev/MudaeFarm#54]
I have a little problem with MudaeFarm. It is not capturing channel messages from a private server in which I participate. It does not even record command information in the console.

- Channel successfully added to bot

![DiscordCanary_UJqYC7yuM5](https://user-images.githubusercontent.com/28351961/66505448-6bbdaf80-ea99-11e9-908d-2b189a903c67.png)

- Message $tu not logged

![WlF9s2j0Sc](https://user-images.githubusercontent.com/28351961/66505451-6ceedc80-ea99-11e9-8de4-481950f2472d.png)

Works normally on other channels.

I don't think it's a matter of permissions, the user has full permission and so does the bot. Maybe incompatibility with Mudamaid#1304?

![DiscordCanary_tCtHKNeQNR](https://user-images.githubusercontent.com/28351961/66505709-e25aad00-ea99-11e9-97b0-91b8df0793d0.png)

Sorry english, i used the xd translator

**Comment by HiseTake** [comment]
I added Mudamaid#1304 on my server and found that MudaeFarm does not recognize messages from it.

Here is the link for bot use
https://discordapp.com/oauth2/authorize?client_id=479206206725160960&permissions=537159744&scope=bot

**Comment by phosphene47** [comment]
Looks like the [maid regex](https://github.com/chiyadev/MudaeFarm/blob/master/MudaeFarm/MudaeInfo.cs) doesn't match for this one.
