### ISSUE TITLE
Mudae IDs

### ISSUE THREAD

**Issue by whatcode123** [chiyadev/MudaeFarm#6]
Since the bot was updated, where do we put the Mudae IDs in the program now?

**Comment by phosphene47** [comment]
The bot is able to detect Mudae automatically.

**Comment by whatcode123** [comment]
I noticed it isn't detecting MudaeMaid3, but it's detecting MudaeMaid23. 

Is there also a way to turn disable a Mudae on one server but have it on for another? They're both diff maids.

**Comment by phosphene47** [comment]
That sounds like a bug. What's the exact username of the maid? Is it `Mudaemaid3` or `Mudaemaid 3`? A screenshot would also be helpful.

As for disabling MudaeFarm in a specific server, you can't do it yet (#7).

**Comment by whatcode123** [comment]
Mudamaid3#4075
https://i.imgur.com/nYpkF2S.png

**Comment by phosphene47** [comment]
Thanks for the report. The latest `Program.cs` should fix this bug. If not, feel free to reopen.
