### ISSUE TITLE
Bot not rolling

### ISSUE THREAD

**Issue by Mattlau04** [chiyadev/MudaeFarm#60]
Hi, i tried using the bot but it just won't roll for waifus even though i have multiples rolls left
I did enable Rolling in my config then restarted but it still doesn't work

**Comment by phosphene47** [comment]
Logs? Configuration? Anything to be helpful?

Please post the logs saved in `_logs.txt`.

**Comment by Mattlau04** [comment]
Here is my config and logs: ![image](https://user-images.githubusercontent.com/37871312/66872442-54555980-efa6-11e9-94b6-f335f0f5affd.png)
![image](https://user-images.githubusercontent.com/37871312/66872462-5fa88500-efa6-11e9-8762-b5972d80f1bc.png)
[_log.txt](https://github.com/chiyadev/MudaeFarm/files/3731600/_log.txt)

**Comment by Mattlau04** [comment]
okay the issue just fixed itself after letting the bot run for a few hours
Really cool bot btw, GG!
