### ISSUE TITLE
Other wishlist does not work

### ISSUE THREAD

**Issue by Ibarakidoji** [chiyadev/MudaeFarm#65]
Other wish list does not work, nothing is happening

**Comment by phosphene47** [comment]
What is meant by "other wish list"?

**Comment by Ibarakidoji** [comment]
I mean wishlist user

**Comment by phosphene47** [comment]
Are you talking about the wishlist configured in `#wishlist-users`? If so, have you configured it correctly using the user ID? Have you configured the bot correctly and enabled autorolling at all?

Can you send a screenshot of the character message that was supposed to be claimed? Can you post the log file (`_logs.txt`)?

Please consider being more specific. Additional details will make solving issues a lot easier.

**Comment by Ibarakidoji** [comment]
I disabled auto rolling,
I put the user id then it changes into an @

**Comment by phosphene47** [comment]
Are you sure the user you configured has a public wishlist? It will not work if the wishlist is private.

**Comment by Ibarakidoji** [comment]
it's public, and my own wishlist does not work

**Comment by phosphene47** [comment]
> Please consider being more specific. Additional details will make solving issues a lot easier.

Closing as lacking requested details.
