### ISSUE TITLE
Add a character blacklist channel

### ISSUE THREAD

**Issue by Mattlau04** [chiyadev/MudaeFarm#71]
It would be really usefull for when you want to add an anime in #wanted-anime but didn't want 1 or two of the chararcters (right now you have to manually add all the characters except the one you don't want and it takes forever)

**Comment by phosphene47** [comment]
I don't like the idea of adding another channel for blacklisting characters. It can be ambiguous if whitelist or blacklist takes priority over the other.

Instead, I think adding a filter expression after the anime name would be better. e.g.

```
gochuumon wa usagi desu ka |excluding chino kafuu, cocoa hoto
```
