### ISSUE TITLE
Make the bot claim the last roll before claim reset

### ISSUE THREAD

**Issue by Mattlau04** [chiyadev/MudaeFarm#74]
Hard to explain in a title but basicly, when you're rolling and it's your last roll, and the next roll reset will happen after the next claim reset, the bot should claim the last character so the claim isn't lost (and maybe divorce it right after so you get some extra kakera)

**Comment by phosphene47** [comment]
Divorcing may be a little difficult.

**Comment by phosphene47** [comment]
With MudaeFarm 4 rolling is now batched, so this issue does not make sense anymore.
