### ISSUE TITLE
What is the correct syntax to not claim multiple characters from an anime?

### ISSUE THREAD

**Issue by Mattlau04** [chiyadev/MudaeFarm#76]
i assume it's this but there is no real way to test :/
`Sakurasou no Pet na Kanojo (excluding: Kazuki Fujisawa,Jin Mitaka)`

**Comment by phosphene47** [comment]
This is correct.

Quoting the README file:
> - You can exclude specific characters for one anime. e.g. `is the order a rabbit? (excluding: kafuu chino)` will allow claiming every character from "Is the Order a Rabbit?" *except* "Kafuu Chino". Glob expressions will not work in this case.

**Comment by Mattlau04** [comment]
the README only specify for a single character so i wasn't sure for when there is multiple
thanks for the quick reply!
