### ISSUE TITLE
Bot will not start after updating to version 2.5.0

### ISSUE THREAD

**Issue by set44599** [chiyadev/MudaeFarm#78]
verbose log: https://pastebin.com/1YWnpmMj 

Windows 10 1809.17763.864
USA

#77 noticed it's going on for this guy + his other issue as well, but here's my log.

**Comment by phosphene47** [comment]
Thank you, but we do not need duplicate issues. Posting this as a comment is fine.

**Comment by set44599** [comment]
ah I see sorry, I thought his issue was different
