### ISSUE TITLE
How to stop the bot from self updating?

### ISSUE THREAD

**Issue by Socialaias** [chiyadev/MudaeFarm#83]
I've been having an issue similar to #81, and wanted to know how to stop it from self updating.

**Comment by phosphene47** [comment]
Run the latest version which will create the config server. Change `auto_update` to `false` from there.

**Comment by set44599** [comment]
2.5.0 does not respect the auto update setting, I even recreated my server with 2.5.1 to see if that would help but 2.5.0 just immediately updates without checking that channel.
