### ISSUE TITLE
WIsh issue with the bot

### ISSUE THREAD

**Issue by thatonecookie** [chiyadev/MudaeFarm#85]
I put my id in the wishlist users channel one of my wishes rolled but i rolled them without the bot rolling for me does it only count if the bot rolls them?

**Comment by phosphene47** [comment]
No, but your wishlist must be public so that the bot knows that it's your wish. The bot knows your wishes if the roll says:

```
Wished by: @your_username
(character image)
```

**Comment by thatonecookie** [comment]
> No, but your wishlist must be public so that the bot knows that it's your wish. The bot knows your wishes if the roll says:
> 
> ```
> Wished by: @your_username
> (character image)
> ```

It did end up saying that 
![image](https://user-images.githubusercontent.com/43299487/72129378-aa366500-333b-11ea-9772-5ef2a942a31e.png)
![image](https://user-images.githubusercontent.com/43299487/72129404-b6222700-333b-11ea-8b56-91d7989bda2d.png)

**Comment by ThatEvil** [comment]
Is there a discord to contact u better sorry im new to all of this

**Comment by phosphene47** [comment]
Fixed in [v4](https://github.com/chiyadev/MudaeFarm/releases/tag/v4.0.0).
