### ISSUE TITLE
Ability to disable kakera collecting

### ISSUE THREAD

**Issue by Mementories** [chiyadev/MudaeFarm#86]
I would like to turn off the kakera collecting, but everytime I put false, it also causes the bot to stop claiming characters. I tried removing the kakera targets but it still collects the kakera.

**Comment by phosphene47** [comment]
There is a temporary workaround: https://github.com/chiyadev/MudaeFarm/issues/82#issuecomment-573032721

**Comment by phosphene47** [comment]
Actually, I am starting to feel that removing all kakera targets is not a bad solution. It does exactly what is expected, and I won't need to add another field in the configuration.
