### ISSUE TITLE
The bot continues to roll even when there are no rolls remaining

### ISSUE THREAD

**Issue by FlameKaito** [chiyadev/MudaeFarm#87]
The bot continues to roll even when there are no rolls remaining

**Comment by FlameKaito** [comment]
I have everything maxed out and premium btw so I have 27 rolls and the mk command

**Comment by phosphene47** [comment]
Log files? Configuration? System information?

Closing until information provided.

**Comment by FlameKaito** [comment]
General
{
  "enabled": true,
  "fallback_status": "DoNotDisturb",
  "state_update_command": "$tu"
}
Claiming
{
  "enabled": true,
  "delay_seconds": 0.1,
  "kakera_delay_seconds": 0.2,
  "kakera_targets": [
    "Purple",
    "Blue",
    "Teal",
    "Green",
    "Yellow",
    "Orange",
    "Red",
    "Rainbow"
  ],
  "enable_custom_emotes": false
}
Rolling
{
  "enabled": false,
  "command": "$m",
  "roll_with_no_claim": false,
  "daily_kakera_enabled": true,
  "daily_kakera_command": "$dk",
  "daily_kakera_then_state_update": true,
  "typing_delay_seconds": 0.1,
  "interval_override_minutes": 0.0
}
Miscellaneous
{
  "auto_update": true
}

**Comment by FlameKaito** [comment]
[warn] [01:39:22] MudaeFarm v3.0.0 by chiya.dev
[info] [01:39:22] User token loaded from: C:\Users\flame\AppData\Local\MudaeFarm\auth_token.txt
[info] [01:39:22] Discord.Net v2.1.1 (API v6)
[info] [01:39:23] Connecting
[warn] [01:39:24] Unknown Dispatch (SESSIONS_REPLACE)
[warn] [01:39:24] Logged in as: Smoothie (291726185199697931)
[info] [01:39:25] Connected
[info] [01:39:25] Ready
[info] [01:39:25] Configuration channel '#information' reloaded in 238.53ms.
[info] [01:39:25] Disconnecting
[info] [01:39:25] Disconnected
[info] [01:39:25] Configuration channel '#wished-characters' reloaded in 81.03ms.
[info] [01:39:25] Configuration channel '#wished-anime' reloaded in 72.16ms.
[info] [01:39:25] Configuration channel '#bot-channels' reloaded in 91.16ms.
[info] [01:39:25] Configuration channel '#claim-replies' reloaded in 85.93ms.
[info] [01:39:25] Configuration channel '#wishlist-users' reloaded in 78.10ms.
[info] [01:39:25] Configuration loaded in 681.65ms.
[warn] [01:39:25] Waiting for connection to stabilize...
[info] [01:39:26] Connecting
[warn] [01:39:26] Failed to resume previous session
[dbug] [01:39:27] patience...
[warn] [01:39:28] Failed to resume previous session
[info] [01:39:29] Ready
[info] [01:39:29] Connected
[warn] [01:39:29] Unknown Dispatch (SESSIONS_REPLACE)
[dbug] [01:39:30] patience...
[dbug] [01:39:32] patience...
[warn] [01:39:34] Failed to resume previous session
[dbug] [01:39:34] patience...
[info] [01:39:35] Ready
[warn] [01:39:35] Unknown Dispatch (SESSIONS_REPLACE)
[dbug] [01:39:36] patience...
[dbug] [01:39:36] nearly there... 3
[dbug] [01:39:38] nearly there... 2
[dbug] [01:39:41] nearly there... 1
[info] [01:39:43] Connected stabilized in 17.86s.
[info] [01:39:43] Champlain Anime Club #waifus-husbandos: Not rolling '$m' because we cannot claim.
[dbug] [01:39:43] Sent state update command '$tu' in channel #waifus-husbandos.
[dbug] [01:39:43] Guild 'Champlain Anime Club' state updated: {"claim_reset":"2020-01-15T01:46:43.8846903-04:00","claim_can":true,"rolls_left":0,"rolls_reset":"2020-01-15T01:46:43.8846903-04:00","daily_reset":"9999-12-31T23:59:59.9999999","daily_reset_can":true,"kakera_reset":"9999-12-31T23:59:59.9999999","kakera_power":0.51,"kakera_consumption":0.4,"kakera_can":true,"kakera_stock":7350,"kakera_reset_daily":"2020-01-15T06:04:43.8846903-04:00","kakera_reset_daily_can":false}
[warn] [01:39:47] Unknown User (PRESENCE_UPDATE User=454124334039171103).
[info] [01:39:48] Champlain Anime Club #waifus-husbandos: Rolled '$m'.

**Comment by FlameKaito** [comment]
As you can see, the rolls left are at 0 but it still rolled

**Comment by Abstractedboy** [comment]
I think it has to do with interval_override_minutes, as I used 0.0 to the override with autorolling disabled, and the bot started to roll even with no rolls available.

**Comment by phosphene47** [comment]
Fixed in [v4](https://github.com/chiyadev/MudaeFarm/releases/tag/v4.0.0).
