### ISSUE TITLE
Bot keep sending $tu in the chat

### ISSUE THREAD

**Issue by Mattlau04** [chiyadev/MudaeFarm#88]
it send one every second so it's a great way to get your account banned for spam
![image](https://user-images.githubusercontent.com/37871312/72549262-a735fa00-3890-11ea-98b5-d32e09eb3423.png)
it fixes itself after restart but reoccurs after some times

**Comment by phosphene47** [comment]
This shouldn't be happening at all.

**Comment by phosphene47** [comment]
[v4](https://github.com/chiyadev/MudaeFarm/releases/tag/v4.0.0) no longer uses `$tu`.
