### ISSUE TITLE
unkown user presence

### ISSUE THREAD

**Issue by lmitless** [chiyadev/MudaeFarm#89]
Is this a joke? I'm pannicking what should i do
![unkn](https://user-images.githubusercontent.com/60331866/73145489-ccebac00-40a5-11ea-8f51-88883286b6ad.png)

**Comment by phosphene47** [comment]
Care to elaborate?

**Comment by lmitless** [comment]
I followed the steps in setup added my token and initiated the setup by running mudaefarm.exe and next thing i know it shows me that.

**Comment by lmitless** [comment]
what can be accomplished with a token?

**Comment by phosphene47** [comment]
Your token is required for the bot to log in to Discord as you. It's your credentials to authorization, like a password.

Also, MudaeFarm is not a "joke". The logs shown in the console are merely warnings, and you can usually ignore them.

> A bulk delete even has been received, but the event handling behavior has not been set.

This is an "event" (synonymous to *indication*) that one of the bots in a server had done a bulk delete, not that MudaeFarm is doing a bulk delete.

**Comment by phosphene47** [comment]
I am closing this issue as this is **normal behavior**. Warnings in the logs can be safely ignored. But if you have any other questions, feel free to ask further.
