### ISSUE TITLE
Assistance needed

### ISSUE THREAD

**Issue by wamez** [chiyadev/MudaeFarm#91]
My wish got outsniped on 0.2 delay. So I'm trying to change it to 0.1 how do i go about doing this. Will sending "delay_seconds": 0.1 in information channel be enough to do this or is there something else I need to do. Thank you in advance and if you could just send it so i could copy paste it somewhere i'd be grateful since I'm not really skilled with things like this.

**Comment by phosphene47** [comment]
To change configuration, you simply edit the message *itself* that contains configuration data. To do this, you can right-click on the message and click "Edit".

Refer to [this page](https://github.com/chiyadev/MudaeFarm/blob/master/README.md#configuration) for a full list of configurable things. Namely, you are looking for the `delay_seconds` in Claiming section.

**Comment by phosphene47** [comment]
Closing as assumed resolved.
