### ISSUE TITLE
Support for Multiple configurations?

### ISSUE THREAD

**Issue by ssj4maiko** [chiyadev/MudaeFarm#93]
I was wondering if it would be possible to make it work with 2 or more different configurations, maybe by creating 2 or more servers with the same configuration content, or finding a way to share some while separating others.

One time I tried to activate the auto rolling, but it started going a little crazy with the commands, so I deactivated, but I thought about making some extra tests in a separate private server, but I didn't want to share the same settings with the main one.

I guess mostly just a suggestion

**Comment by phosphene47** [comment]
This is feasible, but how would MudaeFarm determine which configuration to use at startup?

> One time I tried to activate the auto rolling, but it started going a little crazy with the commands

It would be great if you could make a separate issue in detail for me to investigate this.

**Comment by ssj4maiko** [comment]
With the idea of clone server:

The app searches for servers with the usual necessary channels.
Finds Server 1, with specific information, wished characters/anime, to run those in "bot-channels" and so on.
Finds Server 2, with its own specific information, wish characters/anime, to run those on other "bot-channels" and so on.

-----

With the idea of just different configurations:

Add a new #global-information channel, for universal options and a new attribute {profiles : [ 'Default', 'Channel A', 'High Pace']} (Using just as examples)
Clone the default non-shared channels (#information and #bot-channels most likely, or all of them) with a prefix (#Channel A-information, #Channel A-bot-channels, #High Pace-information, #High Pace-bot-channels, defaulting to non prefixed channel in case it's not found).

The point in both cases is that you will need to keep multiple preferences, and keep both monitoring the channels. I'm not sure how it's implemented now to give a better idea, anyway, these are just suggestion.

-----

> It would be great if you could make a separate issue in detail for me to investigate this.
I didn't had the initial intention of using that function, but I think I think I added $ru into the command and it started spamming it in the channel. I rapidly closed it and turned it off. I didn't want to try it in the main server, hence the idea of having two, one for tests.

**Comment by phosphene47** [comment]
To clarify, is the purpose of having multiple configurations:

- to have layered configuration servers that are merged together in some order, or
- to have different configuration "profiles" that are selected at bot startup

In the former case, it is difficult to implement due to the way the configuration management logic is currently written. It would become significantly more complex, and I'm not sure if it's worth the effort to support such niche usage.

In the latter case, I think I can add a kind of "redirect" message from one configuration server to another. e.g. in the configuration server of User A, add a redirect to the configuration server of User B, and they would share the exact same configuration. User A must join User B's server beforehand. You can still have quasi-user-specific bot channels since inaccessible channels would be ignored.

**Comment by ssj4maiko** [comment]
Sorry about the late reply here.

I guess it's easier to describe it as isolation. There is a server that I want to run with less automated settings, and another server that I want full automation.

- One account (because I can't run 2 different accounts anyway)
- 2 servers completely unrelated between each other
- completely different settings (or at least the ones related to behavior) for each.

Settings from one are not to interfere with the other, for example, one can auto roll, the other cannot, stuff like that.

I guessed that it would be related to how the current settings are implemented. I had an idea of encapsulating everything and merely running multiple copies that would keep their respective settings in their own object, but I'm not sure how are things in C#

**Comment by phosphene47** [comment]
I think I can add a prompt on bot startup to select which configuration server to use, and the ability to create a new one.

**Comment by ssj4maiko** [comment]
The idea was to be able to let them work all the time, or something like that.

I keep the bot running on a tablet (Also running a 48h Black Screen on youtube when not in use), so while I play mostly through my phone or desktop, the bot itself is always out of range. It's good to be able to change the configurations via Server, but at the same time I lose the ability to restart it when it sometimes stops, plus, because I made a test server to experiment on the kakera loots, I wanted to get the bot to continue rolling, claiming and getting all kakera and so on by itself without impacting other servers.

I think a profile option has very limited usability too.

**Comment by phosphene47** [comment]
By "profiles" I'm assuming you mean configuration servers?

> I can add a prompt on bot startup to select which configuration server to use

This is the "profile" selection that I can implement.

> It's good to be able to change the configurations via Server, but at the same time I lose the ability to restart it

You won't need to restart the bot to use multiple profiles, if I understand you correctly. One instance of the bot can only select one profile, but you *can* start multiple instances of the bot with different profiles.

i.e. you can start two MudaeFarm.exe with Profile A and Profile B respectively, and they won't ever interfere with each other.

(That is as long as Profile A and B are mutually exclusive; if they are configured to claim in the same server and characters, it would likely result in double claims or other undefined behavior.)

**Comment by ssj4maiko** [comment]
I see, I hadn't understood what you meant, so basically, I can start one with a profile with behavior "normal", then start another instance with behavior "full auto". And that doesn't conflict with the limitation of a single account (Since the password is saved on the Users\<name>\AppData\Local\MudaeFarm\, meaning all instances will use that password).

**Comment by phosphene47** [comment]
That's the concept. You can configure profiles for different accounts though. Profiles will provide complete isolation.

**Comment by phosphene47** [comment]
Ignore my last comment which was incorrect.

> I can start one with a profile with behavior "normal", then start another instance with behavior "full auto".

That's the concept.

> meaning all instances will use that password

Unless you need support for multiple accounts, in which case I will add support for it.

**Comment by phosphene47** [comment]
See [v3.1.0](https://github.com/chiyadev/MudaeFarm/releases/tag/v3.1.0).

**Comment by ssj4maiko** [comment]
Just tried it here, and was able to properly understand how it works, the instructions were a little confusing at first, but it's likely because I misunderstood how they would be used.

So started it with the default profile first (noticed it had already auto updated), but as I tried to add a new profile, I understood that I needed to actually NOT HAVE a default profile. renamed it, logged in, and got a new server. Copied the content of the title to the original server, restarted it, and it worked fine.

Decided to open another one, and got a failure, because MudaeFarm.log is being used by another process, it throws an error.

**Comment by phosphene47** [comment]
> Decided to open another one, and got an error, because MudaeFarm.log is being used by another process, it throws an error.

> Copying all the files to another folder, running and selecting another profile works, not sure if that was how it was supposed to be.

For now, this workaround will consistently work. I will fix this in a later update.

> Another question is if it's possible to add the same "profile" check from the title to the other channels.

This is not possible and will not be possible because configuration management was not designed to handle such complex usage. Profiles are useful for completely isolated configuration servers.

> Note, name of the server is not MudaeFarm (<profile name>

The bot doesn't determine which server to use from the server name. It uses `#information` channel's topic, so the server can be named however you like.

> it would create a new server and everything.

The first check MudaeFarm does on all servers to find the right configuration server is whether **you** own it or not. So even if you set up the correct channel topic, it won't pass the ownership test. I will consider relaxing this check in another update.

**Comment by ssj4maiko** [comment]
Thinking about it, I think I understand why the check on ones channel, it would be bad if someone knew the data and created a similar settings on their own server. So I have another suggestion.

Would it be possible to create a setting similar to bot-channels, but for the wished-characters/anime only? So the information will remain in the personal custom server, but they will redirect their preferences to a channel of ID from another server (That they obviously have access).

Although now that I think about it, this could easily be abused for bad stuff... Not sure what's your take on this, I'm using all this on a test server, so the idea is merely to guarantee 24h claims, with kakera inflation on the way, and eventually test kakeraloots with abundance in kakera.

**Comment by phosphene47** [comment]
I will close this because any further work on profiles feels out of scope. Profiles are intended to completely isolate configurations for certain servers or to log in as a different user.

This is an intentional design choice. Relational or overlayed configuration is difficult to implement and it's a niche usage.
