### ISSUE TITLE
Issue claiming characters

### ISSUE THREAD

**Issue by Gintoki56** [chiyadev/MudaeFarm#95]
I put the characters in the channel #wished-characters, but when one of this characters spawn this happens
https://imgur.com/Rya41I3
Any solution? I write the chars in different messages, not all in one

**Comment by phosphene47** [comment]
It means what it means. MudaeFarm won't bother to claim a character if you can't claim it because you're on cooldown.

**Comment by Gintoki56** [comment]
I can claim, thats the problem

**Comment by phosphene47** [comment]
Can you do a `$tu` to refresh the bot? The bot determines whether to claim or not based on that command's output. If `$tu` has you're on cooldown, the bot won't claim.

**Comment by Gintoki56** [comment]
I do $tu now and the same thing happened https://imgur.com/09Q2zop

**Comment by phosphene47** [comment]
Possible workaround for now: set `state_update_command` to `""`.

Can you post `_log.txt` file that's in the same folder as MudaeFarm.exe? I need to have a closer look at the logs.

**Comment by Gintoki56** [comment]
https://imgur.com/G5hegym https://imgur.com/tAoneKW I have open the bot since the morning, that's why the time difference xd

**Comment by phosphene47** [comment]
Can you send a `$tu` command in that server and post a screenshot?

**Comment by Gintoki56** [comment]
https://imgur.com/0S4yxDh

**Comment by phosphene47** [comment]
I mean`$tu` in that server and screenshot on the Discord app.

**Comment by Gintoki56** [comment]
https://imgur.com/kMDjFdD btw I set the status from "$tu" to "" and finally claimed a character, thank you!

**Comment by phosphene47** [comment]
As the provided workaround is working I am closing this issue for now.
