### ISSUE TITLE
Problem when open the bot

### ISSUE THREAD

**Issue by Yamixx** [chiyadev/MudaeFarm#96]
https://imgur.com/HIK0zYa dont appear the option to write the token

**Comment by phosphene47** [comment]
Delete `profiles.json` in `%localappdata%MudaeFarm` folder.

**Comment by Yamixx** [comment]
nothing here xd https://imgur.com/ZOOPFmh

**Comment by phosphene47** [comment]
Can you create a file named `profile.json` in that folder and paste this in?

```json
{
"default": ""
}
```

**Comment by Yamixx** [comment]
https://imgur.com/tGwnkvP same thing xd

**Comment by Sudden0** [comment]
That seems to fix the issue. Must not auto generate the profiles.json correctly for some reason.

**Comment by DannyJiang1** [comment]
Hey, the same issue is going on for me, I made a json file and named is profiles.json, and I pasted the code in it as well, but the error is still happening to me, can you help me? Thanks.
