### ISSUE TITLE
Question about a text I keep getting

### ISSUE THREAD

**Issue by thebalista** [chiyadev/MudaeFarm#97]
So after having the bot open for a bit j get this message " A bulk delete event has been received, but the event handling behavior has not been set. To suppress this message, set the exclusivebulkdelete configuration property this message will only appear once" I want to know if this means anything

**Comment by phosphene47** [comment]
It means what it means. Someone did a bulk delete on discord (probably a bot) and MudaeFarm received an event for it but it won't do anything about it because "event handling behavior has not been set."
